const actionTypes = {
  RESET: 'ADMIN_RESET',
  GET: 'ADMIN_GET',
  GET_BY_ID: 'ADMIN_GET_BY_ID',
  POST: 'ADMIN_POST',
  PUT: 'ADMIN_PUT',
  CHANGE_PASSWORD: 'ADMIN_CHANGE_PASSWORD',
  SAVING: 'ADMIN_SAVING',
  DELETE: 'ADMIN_DELETE',
  REMOVING: 'ADMIN_REMOVING',
  GET_ERROR: 'ADMIN_GET_ERROR',
};

export default actionTypes;


