const actionTypes = {
  RESET_MESSAGE: 'ADMIN_RESET_MESSAGE',
  RESET_MESSAGE_ONLY: 'ADMIN_RESET_MESSAGE_ONLY',
  RESET_ARRAY: 'ADMIN_RESET_ARRAY',
  RESET_SINGLE: 'ADMIN_RESET_SINGLE',
  GET: 'ADMIN_GET',
  GET_BY_ID: 'ADMIN_GET_BY_ID',
  POST: 'ADMIN_POST',
  PUT: 'ADMIN_PUT',
  CHANGE_PASSWORD: 'ADMIN_CHANGE_PASSWORD',
  SAVING: 'ADMIN_SAVING',
  DELETE: 'ADMIN_DELETE',
  REMOVING: 'ADMIN_REMOVING',
  GET_ERROR: 'ADMIN_GET_ERROR',
  CUD_ERROR: 'ADMIN_CUD_ERROR',
};

export default actionTypes;

