const actionTypes = {
  RESET_MESSAGE: 'CLIENT_RESET_MESSAGE',
  RESET_MESSAGE_ONLY: 'CLIENT_RESET_MESSAGE_ONLY',
  RESET_ARRAY: 'CLIENT_RESET_ARRAY',
  RESET_SINGLE: 'CLIENT_RESET_SINGLE',
  GET: 'CLIENT_GET',
  DELETE: 'CLIENT_DELETE',
  REMOVING: 'CLIENT_REMOVING',
  GET_ERROR: 'CLIENT_GET_ERROR',
  CUD_ERROR: 'CLIENT_CUD_ERROR',
};

export default actionTypes;

