const actionTypes = {
  RESET_MESSAGE: 'CATEGORY_RESET_MESSAGE',
  RESET_MESSAGE_ONLY: 'CATEGORY_RESET_MESSAGE_ONLY',
  RESET_ARRAY: 'CATEGORY_RESET_ARRAY',
  RESET_SINGLE: 'CATEGORY_RESET_SINGLE',
  GET: 'CATEGORY_GET',
  GET_BY_ID: 'CATEGORY_GET_BY_ID',
  POST: 'CATEGORY_POST',
  PUT: 'CATEGORY_PUT',
  SAVING: 'CATEGORY_SAVING',
  DELETE: 'CATEGORY_DELETE',
  REMOVING: 'CATEGORY_REMOVING',
  GET_ERROR: 'CATEGORY_GET_ERROR',
  CUD_ERROR: 'CATEGORY_CUD_ERROR',
};

export default actionTypes;
