const actionTypes = {
  RESET_MESSAGE: 'CATEGORY_RESET_MESSAGE',
  RESET_MESSAGE_ONLY: 'CATEGORY_RESET_MESSAGE_ONLY',
  RESET_ARRAY: 'CATEGORY_RESET_ARRAY',
  RESET_SINGLE: 'CATEGORY_RESET_SINGLE',
  GET: 'CATEGORY_GET',
  GET_BY_ID: 'CATEGORY_GET_BY_ID',
  POST: 'CATEGORY_POST',
  PUT: 'CATEGORY_PUT',
  SAVING: 'CATEGORY_SAVING',
  DELETE: 'CATEGORY_DELETE',
  REMOVING: 'CATEGORY_REMOVING',
  GET_ERROR: 'CATEGORY_GET_ERROR',
  CUD_ERROR: 'CATEGORY_CUD_ERROR',
};

export default actionTypes;

/*const actionTypes = {
  RESET_MESSAGE: 'RESET_CATEGORY_MESSAGE',
  RESET_MESSAGE_ONLY: 'RESET_CATEGORY_MESSAGE_ONLY',
  RESET_CATEGORY: 'RESET_CATEGORY',
  RESET_CATEGORIES: 'RESET_PROD_CATS',
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_CATEGORY: 'GET_CATEGORY',
  POST_CATEGORY: 'POST_CATEGORY',
  PUT_CATEGORY: 'PUT_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  GET_CATEGORY_ERROR: 'GET_CATEGORY_ERROR',
};

export default actionTypes;*/
