const actionTypes = {
  RESET: "CATEGORY_RESET",
  GET: "CATEGORY_GET",
  GET_BY_ID: "CATEGORY_GET_BY_ID",
  POST: "CATEGORY_POST",
  PUT: "CATEGORY_PUT",
  SAVING: "CATEGORY_SAVING",
  DELETE: "CATEGORY_DELETE",
  REMOVING: "CATEGORY_REMOVING",
  GET_ERROR: "CATEGORY_GET_ERROR",
};

export default actionTypes;
