const actionTypes = {
  RESET_MESSAGE: 'AUTH_RESET_MESSAGE',
  SIGN_IN: 'AUTH_SIGN_IN',
  LOG_OUT: 'AUTH_LOG_OUT',
  RESET_PASSWORD: 'AUTH_RESET_PASSWORD',
  CHANGE_PASSWORD: 'AUTH_CHANGE_PASSWORD',
  GET_ERROR: 'AUTH_GET_ERROR',
};

export default actionTypes;
