const actionTypes = {
  RESET_MESSAGE: 'PRODUCT_RESET_MESSAGE',
  RESET_MESSAGE_ONLY: 'PRODUCT_RESET_MESSAGE_ONLY',
  RESET_ARRAY: 'PRODUCT_RESET_ARRAY',
  RESET_SINGLE: 'PRODUCT_RESET_SINGLE',
  GET: 'PRODUCT_GET',
  GET_BY_ID: 'PRODUCT_GET_BY_ID',
  POST: 'PRODUCT_POST',
  PUT: 'PRODUCT_PUT',
  SAVING: 'PRODUCT_SAVING',
  DELETE: 'PRODUCT_DELETE',
  REMOVING: 'PRODUCT_REMOVING',
  GET_ERROR: 'PRODUCT_GET_ERROR',
  CUD_ERROR: 'PRODUCT_CUD_ERROR',
};

export default actionTypes;
