const actionTypes = {
  RESET: 'PRODUCT_RESET',
  GET: 'PRODUCT_GET',
  GET_BY_ID: 'PRODUCT_GET_BY_ID',
  POST: 'PRODUCT_POST',
  PUT: 'PRODUCT_PUT',
  SAVING: 'PRODUCT_SAVING',
  DELETE: 'PRODUCT_DELETE',
  REMOVING: 'PRODUCT_REMOVING',
  GET_ERROR: 'PRODUCT_GET_ERROR',
};

export default actionTypes;
